version: '3.7'

services:
  node-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/node-app/src
    container_name: node-server
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run dev